
###################################################
# this(CMakeTestAutoGeneration.cmake) is automatically generated by 'auto_ctest_impl.py'. 
# The behavior of modifying this file is undefined.
###################################################
message(STATUS "load ctests automatic generated success")

add_test(NAME "${CMAKE_BINARY_DIR}/test_fresnel" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src ${CMAKE_BINARY_DIR}/test_fresnel")
set_tests_properties("${CMAKE_BINARY_DIR}/test_fresnel" PROPERTIES LABELS "golden;")
    
add_test(NAME "${CMAKE_BINARY_DIR}/test_nearfield" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src ${CMAKE_BINARY_DIR}/test_nearfield")
set_tests_properties("${CMAKE_BINARY_DIR}/test_nearfield" PROPERTIES LABELS "golden;")
    
add_test(NAME "${CMAKE_BINARY_DIR}/test_optical" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src ${CMAKE_BINARY_DIR}/test_optical")
set_tests_properties("${CMAKE_BINARY_DIR}/test_optical" PROPERTIES LABELS "golden;")
    
add_test(NAME "${CMAKE_BINARY_DIR}/test_polar" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src ${CMAKE_BINARY_DIR}/test_polar")
set_tests_properties("${CMAKE_BINARY_DIR}/test_polar" PROPERTIES LABELS "golden;")
    
add_test(NAME "${CMAKE_BINARY_DIR}/test_polynomials" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src ${CMAKE_BINARY_DIR}/test_polynomials")
set_tests_properties("${CMAKE_BINARY_DIR}/test_polynomials" PROPERTIES LABELS "golden;")
    
add_test(NAME "${CMAKE_BINARY_DIR}/test_pupil" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src ${CMAKE_BINARY_DIR}/test_pupil")
set_tests_properties("${CMAKE_BINARY_DIR}/test_pupil" PROPERTIES LABELS "golden;")
    
add_test(NAME "${CMAKE_BINARY_DIR}/test_source" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src ${CMAKE_BINARY_DIR}/test_source")
set_tests_properties("${CMAKE_BINARY_DIR}/test_source" PROPERTIES LABELS "golden;")
    
add_test(NAME "${CMAKE_BINARY_DIR}/test_tmm" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src ${CMAKE_BINARY_DIR}/test_tmm")
set_tests_properties("${CMAKE_BINARY_DIR}/test_tmm" PROPERTIES LABELS "golden;")
    
add_test(NAME "${CMAKE_BINARY_DIR}/test_zernike_m_1_l_1" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src ${CMAKE_BINARY_DIR}/test_zernike m 1 l 1")
set_tests_properties("${CMAKE_BINARY_DIR}/test_zernike_m_1_l_1" PROPERTIES LABELS "golden;")
    
add_test(NAME "${CMAKE_BINARY_DIR}/test_simulation" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src ${CMAKE_BINARY_DIR}/test_simulation")
set_tests_properties("${CMAKE_BINARY_DIR}/test_simulation" PROPERTIES LABELS "golden;")
    